steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/debug-proxy', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/debug-proxy']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'debug-proxy', 
  '--image', 'gcr.io/$PROJECT_ID/debug-proxy', 
  '--region', 'us-central1', 
  '--platform', 'managed', 
  '--allow-unauthenticated'
  ]
images:
- gcr.io/$PROJECT_ID/debug-proxy
